W0204 15:50:30.003000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0] Backend compiler failed with a fake tensor exception at 
W0204 15:50:30.003000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0]   File "./generated/test_cure_lab_MagicDrive.py", line 6398, in forward
W0204 15:50:30.003000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0]     return output_tensor
W0204 15:50:30.003000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0] Adding a graph break.
W0204 15:50:30.021000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0_1] Backend compiler failed with a fake tensor exception at 
W0204 15:50:30.021000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0_1]   File "./generated/test_cure_lab_MagicDrive.py", line 6398, in forward
W0204 15:50:30.021000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0_1]     return output_tensor
W0204 15:50:30.021000 2114025 site-packages/torch/_dynamo/exc.py:304] [0/0_1] Adding a graph break.
W0205 20:39:51.437000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0] Backend compiler failed with a fake tensor exception at 
W0205 20:39:51.437000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0]   File "./generated/test_cure_lab_MagicDrive.py", line 6398, in forward
W0205 20:39:51.437000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0]     return output_tensor
W0205 20:39:51.437000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0] Adding a graph break.
W0205 20:39:51.454000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0_1] Backend compiler failed with a fake tensor exception at 
W0205 20:39:51.454000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0_1]   File "./generated/test_cure_lab_MagicDrive.py", line 6398, in forward
W0205 20:39:51.454000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0_1]     return output_tensor
W0205 20:39:51.454000 3650527 site-packages/torch/_dynamo/exc.py:304] [0/0_1] Adding a graph break.
